name: CICD
on:
 workflow_dispatch:
   inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production
   

jobs:
    code:
       runs-on: ubuntu-latest
       steps:
         - name: checkout code
           run: echo "copy the code from github"
    build:
       needs: [code]
       runs-on: ubuntu-latest
       steps:
         - name: build the code
           run: echo "copy the code from github"     

    test:
       needs: [code,build]
       runs-on: ubuntu-latest
       steps:
         - name: test the code
           run: echo " copy the code from github"


    deploy:
       if: inputs.environment == 'deploy'
       needs: [code,build,test]
       runs-on: ubuntu-latest
       steps:
         - name: deploy code
           run: echo "copy the code from github"

           
