name: devsecops-pipeline

on:
    workflow_dispatch

jobs:
    code-checkout:
         uses: ./.github/workflows/code-quality.yml

    secret-scan:
        
         uses: ./.github/workflows/secret-scan.yml
         secrets: inherit
    dependency-scan:
        
          uses: ./.github/workflows/dependency-scan.yml
    docker-lint:
          
          uses: ./.github/workflows/docker-lint.yml
    buildandpush:
         needs: ["code-checkout","secret-scan","docker-lint", "docker-lint"]
         uses: ./.github/workflows/buildandpush.yml
         secrets: inherit
    image-scan:
        
         uses: ./.github/workflows/image-scan.yml
         secrets: inherit
