name: docker-lint

on:
    workflow_call

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v6
            - name: Install Hardolint
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile