name: Hello workflow

on:
  workflow_dispatch: 

jobs:
   greet:
     runs-on: ubuntu-latest
     steps:
       - name: "hello Dosto"
         run: echo "hello dosto"

       - name: "say hello to user"
         run: echo "hello $USER"

   job2:
      runs-on: ubuntu-latest
      steps:
         - name: Versions of python and docker
           run: docker --version && python --version
   
  
